# Docs: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
updates:
  -
    directory: /
    open-pull-requests-limit: 0
    package-ecosystem: gradle
    schedule:
      interval: daily
  -
    directory: /modules
    open-pull-requests-limit: 0
    package-ecosystem: gradle
    schedule:
      interval: daily
  -
    directory: /server
    open-pull-requests-limit: 0
    package-ecosystem: gradle
    schedule:
      interval: daily
  -
    directory: /plugins
    open-pull-requests-limit: 0
    package-ecosystem: gradle
    schedule:
      interval: daily
version: 2
