# 'true' will fix files
autofix: true

ignore:
  - .git/
  - .gradle/
  - '*.sha1'
  - '*.txt'
  - '.github/CODEOWNERS'
  - 'buildSrc/src/testKit/opensearch.build/LICENSE'
  - 'buildSrc/src/testKit/opensearch.build/NOTICE'
  - 'server/licenses/apache-log4j-extras-DEPENDENCIES'
  #Empty files
  - 'doc-tools/missing-doclet/bin/main/org/opensearch/missingdoclet/MissingDoclet.class'
  - 'buildSrc/src/integTest/resources/org/opensearch/gradle/internal/fake_git/remote/build.gradle'
  - 'buildSrc/src/integTest/resources/org/opensearch/gradle/internal/fake_git/remote/distribution/archives/oss-darwin-tar/build.gradle'
  - 'buildSrc/src/integTest/resources/org/opensearch/gradle/internal/fake_git/remote/distribution/bwc/bugfix/build.gradle'
  - 'buildSrc/src/integTest/resources/org/opensearch/gradle/internal/fake_git/remote/distribution/bwc/minor/build.gradle'
  - 'buildSrc/src/main/resources/buildSrc.marker'
  - 'buildSrc/src/testKit/opensearch-build-resources/settings.gradle'
  - 'buildSrc/src/testKit/opensearch.build/settings.gradle'
  - 'buildSrc/src/testKit/reaper/settings.gradle'
  - 'buildSrc/src/testKit/symbolic-link-preserving-tar/settings.gradle'
  - 'client/rest-high-level/src/main/resources/META-INF/services/org.opensearch.plugins.spi.NamedXContentProvider'
  - 'distribution/bwc/bugfix/build.gradle'
  - 'distribution/bwc/maintenance/build.gradle'
  - 'distribution/bwc/minor/build.gradle'
  - 'distribution/bwc/staged/build.gradle'
  - 'libs/ssl-config/src/test/resources/certs/pem-utils/empty.pem'
  - 'qa/evil-tests/src/test/resources/org/opensearch/common/logging/does_not_exist/nothing_to_see_here'
  - 'qa/os/centos-6/build.gradle'
  - 'qa/os/debian-8/build.gradle'
  - 'qa/os/oel-6/build.gradle'
  - 'qa/os/oel-7/build.gradle'
  - 'qa/os/sles-12/build.gradle'

rules:
  # checks if file ends in a newline character
  end-of-file:
    # set to true to enable this rule
    enable: true

    # if true also checks if file ends in a single newline character
    single-new-line: true
