name: "Changelog Verifier"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces the update of a changelog file on every pull request
  verify-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: dangoslen/dependabot-changelog-helper@v1

      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "Update changelog"

      - uses: dangoslen/changelog-enforcer@v3
