name: Gradle Check (Jenkins)
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    timeout-minutes: 130
    steps:
      - uses: actions/checkout@v2
      - name: retrieve xml
        run: curl -SLO https://build.ci.opensearch.org/job/gradle-check/lastSuccessfulBuild/artifact/codeCoverage.xml

      - name: Upload Coverage Report
        if: success()
        uses: codecov/codecov-action@v2
        with:
          files: ./codeCoverage.xml

