name: Link Checker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linkchecker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Load Excludes
        run: |
          EXCLUDES=$(sed -e :a  -e 'N;s/\n/ --exclude /;ta' .lycheeignore)
          echo "EXCLUDES=--exclude $EXCLUDES" >> $GITHUB_ENV

      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@master
        with:
          args: --accept=200,403,429 ${{ env.EXCLUDES }} --exclude-mail "**/*.html" "**/*.md" "**/*.txt" "**/*.json"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
