name: Pull Request Checks

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  verify-description:
    name: Verify Description
    runs-on: ubuntu-latest
    steps:
        - uses: peternied/check-pull-request-description@main
          with:
            checklistItems: |
                New functionality includes testing.
                All tests pass
                New functionality has been documented.
                New functionality has javadoc added
                Commits are signed per the DCO using --signoff
                Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
    